### ISSUE TITLE
Panel spacing doesn't seem to work when using theme_cmap()

### ISSUE THREAD

**Issue by dlcomeaux** [CMAP-REPOS/cmapplot#74]
This is a weird bug, but I've noticed that when I try to add spacing between panels, it doesn't work. What's weirder is that it also adds the numeric value of the spacing you add below the plot.

For example, this yields the following chart:
```
chart2 <- project_type_spending_ratio %>%
  filter(DisplayGroup == "Neither" | DisplayGroup == "EDA and/or DA") %>%
  filter(!(PROJECT.TYPE %in% null_types)) %>%
  filter(ratio_type %in% c("area_ratio","pop_ratio")) %>%
  mutate(ratio_type = case_when(
    ratio_type == "area_ratio" ~ "2. Per acre",
    ratio_type == "pop_ratio" ~ "1. Per capita"
  )) %>%
  ggplot(aes(x = value, y = reorder(PROJECT.TYPE,desc(PROJECT.TYPE)))) +
  geom_bar(aes(fill = DisplayGroup), stat = "identity", position = position_dodge(width = .55), width = .5) +
  facet_grid(~ratio_type,scales = "free") +
  theme_cmap(gridlines = "hv",theme(panel.spacing.x = unit(5,"lines"))) +
  scale_x_continuous(labels = scales::label_dollar()) +
  cmap_fill_discrete(palette = "governance")
```
![image](https://user-images.githubusercontent.com/58892984/97755877-ece24d00-1ac7-11eb-8466-ad2136611877.png)

I can try to look into this, but does anyone have any initial ideas? @matthewstern @nmpeterson ? Maybe this will get solved by having a complete theme? (We can hope)

**Comment by matthewstern** [comment]
@dlcomeaux, instead of the line:
`theme_cmap(gridlines = "hv",theme(panel.spacing.x = unit(5,"lines")))`
Try:
`theme_cmap(gridlines = "hv", panel.spacing.x = unit(5,"lines"))`

Additionally, try reinstalling from the branch with the complete them, which should be:
```
devtools::install_github("CMAP-REPOS/cmapplot", ref="fontsizes")
library(cmapplot)
```

The way I've set up the `...`, `theme_cmap()` is expecting the actual theme arguments themselves, not an instance of the `theme` function. (although that would have been a decent way to do it...)

**Comment by dlcomeaux** [comment]
Oops, good call. Thanks!
