### ISSUE TITLE
warning when specifying aes in geom_text_lastonly

### ISSUE THREAD

**Issue by matthewstern** [CMAP-REPOS/cmapplot#76]
In this ggplot, the text for `geom_text_lastonly` is selected automatically/by default in some way that I am not familiar with:

```
ggplot(data = df, 
       mapping = aes(x = year, y = ridership, color = system)) +
  geom_recessions(ymin = 0) +
  geom_line(size = 1) +
  theme_cmap(ylab = "Annual Ridership (Millions)") + 
  geom_text_lastonly(add_points = TRUE,
                     nudge_x = 0.5) +
  coord_cartesian(clip = "off")
```

However, if the user wants to specify/customize the text, I believe `label` must be specified in `aes()`, such as this:
```
ggplot(data = df, 
       mapping = aes(x = year, y = ridership, color = system, label = round(ridership, digits = 0))) +
  geom_recessions(ymin = 0) +
  geom_line(size = 1) +
  theme_cmap(ylab = "Annual Ridership (Millions)") + 
  geom_text_lastonly(add_points = TRUE,
                     nudge_x = 0.5) +
  coord_cartesian(clip = "off")
```

This aes should be able to be specified in either the top-line ggplot (above) or in the geom (below). Interestingly, for me, the following works but throws an error message "Ignoring unknown aesthetics: label".

```
ggplot(data = df, 
            mapping = aes(x = year, y = ridership, color = system)) +
  geom_recessions(ymin = 0) +
  geom_line(size = 1) +
  theme_cmap(ylab = "Annual Ridership (Millions)") + 
  geom_text_lastonly(mapping = aes(label = round(ridership, digits = 0)), 
                     add_points = TRUE,
                     nudge_x = 0.5) +
  coord_cartesian(clip = "off")
```

Why does the warning get triggered?

**Comment by nmpeterson** [comment]
This is because `geom_text_lastonly` is a hybrid of two geoms, `geom_text` and `geom_point`. While `geom_text` has a `label` parameter, `geom_point` does not, hence the error.

- Parameters exclusive to`geom_text`: `angle`, `hjust`, `vjust`, `family`, `fontface`, `lineheight`, and `label`.
- Parameters exclusive to `geom_point`: `shape`, `fill`, and `stroke`.

I guess the easiest solution would be to make sure both geoms accept the same named parameters, even if some get completely ignored by one of the two geoms.
